language: node_js
node_js:
  - "10.13"
dist: trusty
sudo: required
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - npm run test-headless
  - ng build --prod --base-href https://sherrensoesanto.github.io/friends-mgmt-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/friends-mgmt-app
  on:
    branch: master
